model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 16


data_params:
  data_path: "Data/"
  train_batch_size: 2048
  val_batch_size:  2048
  patch_size: 64
  num_workers: 16


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0,1,2,3]
  max_epochs: 100

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
